ldap:
  build: ldap/.
  expose:
    - "389"
  env_file: ldap/auth.env
  restart: always
  labels:
    io.enonic.backup.enable: "yes"
    io.enonic.backup.prescripts: "/usr/local/bin/backup-pre.sh"
    io.enonic.backup.postscripts: "/usr/local/bin/backup-post.sh"
    io.enonic.backup.data: "/backup"
  volumes_from:
    - ldapstorage
ldapstorage:
  build: ldap/.
  volumes:
    - /var/lib/ldap
    - /etc/ldap/init
    - /etc/ldap/slap.d
  command: "echo ldap volume container"
